echo. > plu
echo. > logo
echo. > maingroup
echo. > scrollmessage
echo. > scrollseq
echo. > image
echo. > specmessage
echo. > scalefile
echo. > ingred
echo. > place
echo. > shopname
echo. > preset
echo. > clerk
echo. > department
echo. > advert
echo. > text
echo. > freeformat
echo. > timer
